apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hywbry0su-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hywbry0su-java-quarkus-gitops